config/routes.rb
Wifidemo::Application.routes.draw do
  get "internet/connect"
  get "ad/show"
  root "home#index"

  

end

app/models/ad.rb
class Ad < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/ad_controller.rb
class AdController < ApplicationController
  def show
    @main_ad = Ad.where(name: 'New World Mall').find(&:main)
    @ads = Ad.where(name: 'New World Mall').select{|ad| !ad.main}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/internet_controller.rb
class InternetController < ApplicationController
  def connect
  end
end

app/helpers/ad_helper.rb
module AdHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/internet_helper.rb
module InternetHelper
end

app/views/ad/show.html.erb
  <!-- Main Content Section -->

  <div class="row">

    <div class="large-12 columns" style="text-align: center;">
      <h2>
        <%= @main_ad.name %>
      </h2>
      <p class="subheader"> This internet connection is sponsored by <%= @main_ad.name %> </p>
      <div id="ad-image">
        <a href="<%= @main_ad.url %>" target="_blank">
          <img src="<%= @main_ad.image_url %>" />
        </a>
        <hr />
      </div>

      <div class="row">
        <div class="large-4 columns">
          <%= image_tag @ads[0].image_url %>
          <!-- <img src="http://placehold.it/400x300&#38;text=[img]" /> -->
        </div>

        <div class="large-4 columns">
          <%= image_tag @ads[1].image_url %>
          <!-- <img src="http://placehold.it/400x300&#38;text=[img]" /> -->
        </div>

        <div class="large-4 columns">
          <%= image_tag @ads[2].image_url %>
          <!-- <img src="http://placehold.it/400x300&#38;text=[img]" /> -->
        </div>

      </div>

      <p>
        <div id="countdown"></div>
        <div id='internet-connect-link' style="display:none">
          <a class="button" href="<%= internet_connect_path %>">Connect to the Internet!</a>
        </div>
      </p>

    </div>

    <div class="large-4 columns">
    </div>
  </div>

  <script>
    var timer = 10;
    var timerMessage = setInterval(function(){
      $("#countdown").html("You will be connected to the internet in " + timer + " seconds");
      if (timer >= 0) {
        timer--;
      }
    },1000)

    var pageForward = setTimeout(function(){
      clearInterval(timerMessage);

      $("#countdown").hide();
      $("#internet-connect-link").show();
    },10000)
  </script>

app/views/home/index.html.erb
<!-- Nav and Banner -->

  <div class="row">
    <div class="large-12 columns">

      <!-- Main Banner Image - place in a paragraph to enforce the modular scale spacing -->
      <%= image_tag 'flushing_wifi_logo.png' %>
    </div>
  </div>

  <!-- Main Content Section -->

  <div class="row">

    <div class="large-10 columns" id="login-area">
      <h3>Get Connected to Wi-fi</h3>
      <%= form_for :user, url: "add", html: { class: "sign-in form-horizontal text-left" } do |f| %>
        <div class="control-group">
        <%# <%= f.label :email, class: "control-label" %>
        <%= f.label :email, class: "control-label" %>
        <div class="controls">
          <%# <%= f.email_field :email, :autofocus => true, placeholder: "your@email.com" %>
          <%# <%= f.email_field :encrypted_email, :autofocus => true, placeholder: "your@email.com" %>
          <%= text_field_tag 'email' %>
          <label for="terms-agree">
            <input type="checkbox" id="checkbox1" CHECKED>
            <span class="custom checkbox checked"></span> I agree to the terms and conditions
          </label>
        </div>
      </div>

      <%# <%= submit_tag("Register &rarr;".html_safe, :class => "secondary small button")%>

      <p>
        <%= link_to 'Go Online!', ad_show_path, class: "secondary small button" %>
      </p>
    <% end %>
    </div>

    <div class="large-2 columns hide-for-medium-down">
      <%= image_tag 'phone_wifi.png' %>
    </div>
<!--     <div class="large&#45;4 columns"> -->
<!--       <p><img src="https://dl.dropboxusercontent.com/u/5300360/website/wifidemo/right_banner.png" /></p> -->
<!--     </div> -->

  </div>


  <!-- Call to Action Panel -->
  <div class="row">
    <div class="large-12 columns">

      <div class="panel">
        <h4>Get in touch!</h4>

        <div class="row">
          <div class="large-9 columns">
            <p>We'd love to hear from you.</p>
          </div>
          <div class="large-3 columns">
            <a href="#" class="radius button right">Contact Us</a>
          </div>
        </div>
      </div>

    </div>
  </div>

app/views/internet/connect.html.erb
<h1>You're now connected to the internet!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

  <div class="row">
    <div class="large-12 columns">
      <ul class="button-group">
        <li><a href="#" class="button">Link 1</a></li>
        <li><a href="#" class="button">Link 2</a></li>
        <li><a href="#" class="button">Link 3</a></li>
      </ul>

    <%= yield %>

    </div>
  </div>

  <!-- Footer -->

  <footer class="row">
    <div class="large-12 columns">
      <hr />
      <div class="row">
        <div class="large-6 columns">
          <p>&copy; Copyright KuWifi</p>
        </div>
        <div class="large-6 columns">
          <ul class="inline-list right">
            <li><a href="#">Link 1</a></li>
            <li><a href="#">Link 2</a></li>
            <li><a href="#">Link 3</a></li>
          </ul>
        </div>
      </div>
    </div> 
  </footer>

  <%= javascript_include_tag "application" %>

  </body>
</html>